services:
  - type: web
    name: portafolio_alex_2025
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn backend.portfolio_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.portfolio_backend.settings
      - key: PYTHON_VERSION
        value: 3.12.1
    buildFilter:
      paths:
        - frontend/**
        - backend/**
        - build.sh
        - render.yaml
