# Generated by Django 5.2.4 on 2025-07-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_tag_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='projectvideo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
