# Generated by Django 5.2.4 on 2025-07-31 04:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
