# Generated by Django 5.2.4 on 2025-07-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
