# Generated by Django 5.2.4 on 2025-07-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_extra_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_images',
            field=models.ManyToManyField(blank=True, related_name='projects_with_extra', to='projects.projectimage'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
