# Generated by Django 5.2.4 on 2025-07-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_extra_images_alter_projectimage_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='extra_images',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='projects.project'),
        ),
    ]
