# Generated by Django 5.2.4 on 2025-08-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
